# Generated by Django 4.2.7 on 2025-05-27 15:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recognition.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(help_text='Автоматически генерируется при создании', max_length=20, unique=True, verbose_name='Номер заявки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подана'), ('in_review', 'На рассмотрении'), ('additional_docs_required', 'Требуются дополнительные документы'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Завершена')], default='draft', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('applicant_first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('applicant_last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('applicant_middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('applicant_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('applicant_iin', models.CharField(help_text='Индивидуальный идентификационный номер', max_length=12, verbose_name='ИИН')),
                ('institution_name', models.CharField(max_length=255, verbose_name='Название учебного заведения')),
                ('institution_country', models.CharField(max_length=100, verbose_name='Страна обучения')),
                ('education_level', models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('doctorate', 'Докторантура'), ('specialist', 'Специалитет'), ('other', 'Другое')], max_length=20, verbose_name='Уровень образования')),
                ('specialty', models.CharField(max_length=255, verbose_name='Специальность')),
                ('graduation_year', models.PositiveIntegerField(verbose_name='Год окончания')),
                ('duration_years', models.PositiveIntegerField(verbose_name='Продолжительность обучения (лет)')),
                ('purpose', models.TextField(help_text='Для чего нужно признание документа', verbose_name='Цель признания')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительные комментарии')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на признание',
                'verbose_name_plural': 'Заявки на признание',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('diploma', 'Диплом'), ('transcript', 'Транскрипт/Приложение к диплому'), ('passport', 'Копия паспорта'), ('translation', 'Нотариальный перевод'), ('apostille', 'Апостиль'), ('other', 'Другой документ')], max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=recognition.models.upload_to_recognition, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recognition.recognitionapplication', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Документ заявки',
                'verbose_name_plural': 'Документы заявок',
                'ordering': ['document_type', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подана'), ('in_review', 'На рассмотрении'), ('additional_docs_required', 'Требуются дополнительные документы'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Завершена')], max_length=30, verbose_name='Статус "от"')),
                ('status_to', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подана'), ('in_review', 'На рассмотрении'), ('additional_docs_required', 'Требуются дополнительные документы'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Завершена')], max_length=30, verbose_name='Статус "к"')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='recognition.recognitionapplication', verbose_name='Заявка')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'История заявки',
                'verbose_name_plural': 'История заявок',
                'ordering': ['-changed_at'],
            },
        ),
    ]
